<a href="https://colab.research.google.com/github/DARKINOO/Pytorch_practice/blob/main/tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)

2.8.0+cu126


In [ ]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU : {torch.cuda.get_device_name(0)}")
else:
  print("GPU not available. Using CPU")

GPU is available
Using GPU : Tesla T4


###Creating a Tensor

In [ ]:
# using empty
a = torch.empty(2,3) #here values will be empty

In [ ]:
# Check type
type(a)

torch.Tensor

In [ ]:
# using zeros
torch.zeros(2,3) #here values will initialize with zeroes

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# using ones
torch.ones(2,3) #initializes with ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
#using rand
torch.rand(2,3) #any random value btw 0 and 1 , always diff

tensor([[0.9315, 0.8432, 0.5411],
        [0.6900, 0.9283, 0.1815]])

In [ ]:
#use of seed
torch.manual_seed(100) #those randpm values persists not chnaqges everytime i run code
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]]) #we can initialize

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# other ways
#arange
print("using arange ->", torch.arange(0,10))

#using linspace
print("using linspace ->", torch.linspace(0,10,10))

#using eye
print("using eye ->", torch.eye(5))

#using full
print("using full ->", torch.full((3,3),5))

using arange -> tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


###Tensor Shapes

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x) #gives new tensor with same shape as of x

tensor([[     1097010992, 135008250304128,               1],
        [              6,               0,               0]])

In [ ]:
torch.zeros_like(x) #new tensor with 0 values same shape as x

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
#torch.rand_like(x) #this code will not work coz its genrate float datat type and our tensor is in int
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

###Tensor Data Types

In [ ]:
# find data type
x.dtype

torch.int64

In [ ]:
#assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3], dtype=torch.float32)

tensor([1., 2., 3.])

###Tensor Mathematical operations

In [ ]:
##addition
x = torch.tensor([[1,2,3],[4,5,6]])
x + 3
## subtraction
x - 2
## multiplication
x * 3
## int division
(x*1000)//3
# mod
((x*1000)//3)%2

tensor([[1, 0, 0],
        [1, 0, 0]])

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)
print(a)
print(b)

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])
tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])


In [ ]:
#ALL element wise operations
#add
a+b
#subtract
a-b
#multiply
a*b
#division
a/b

tensor([[3.1790, 2.6049, 2.3445],
        [1.0942, 1.7938, 0.7743]])

In [ ]:
c = torch.tensor([1.9,2.3,3.3,4.4])
torch.abs(c)
torch.neg(c)


tensor([-1.9000, -2.3000, -3.3000, -4.4000])

In [ ]:
torch.round(c)
torch.ceil(c)
torch.floor(c)

tensor([1., 2., 3., 4.])

In [ ]:
#Clamp
torch.clamp(c,min=2,max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

###Reduction operations

In [ ]:
e = torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e

tensor([[5., 9., 9.],
        [7., 5., 9.]])

In [ ]:
#sum
print(torch.sum(e)) #gives sum of whole matrix
print(torch.sum(e,dim=0)) #sum along columns
print(torch.sum(e,dim=1)) #sum along rows

#mean
print(torch.mean(e)) #mean of whole
print(torch.mean(e,dim=0)) #mean of col

#median
print(torch.median(e)) #median of whole

#max & min
print(torch.max(e)) #max of whole
print(torch.min(e)) #min of whole

#product
print(torch.prod(e)) # of whole

#std and variance
print(torch.std(e))
print(torch.var(e))

#argmax - return position of max elem
print(torch.argmax(e))

#argmin - return position of min elem
print(torch.argmin(e))

tensor(44.)
tensor([12., 14., 18.])
tensor([23., 21.])
tensor(7.3333)
tensor([6., 7., 9.])
tensor(7.)
tensor(9.)
tensor(5.)
tensor(127575.)
tensor(1.9664)
tensor(3.8667)
tensor(1)
tensor(0)


###Matrix Operations

In [ ]:
f = torch.randint(size=(2,3), low=0,high=10)
g = torch.randint(size=(3,2), low=0,high=10)

print(f)
print(g)

tensor([[8, 9, 7],
        [9, 2, 6]])
tensor([[7, 7],
        [8, 3],
        [6, 1]])


In [ ]:
#matrix multiplication
torch.matmul(f,g)

tensor([[170,  90],
        [115,  75]])

In [ ]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

#dot product
torch.dot(vector1,vector2)

tensor(11)

In [ ]:
#transpose
torch.transpose(f,0,1)


tensor([[8, 9],
        [9, 2],
        [7, 6]])

In [ ]:
h = torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
print(h)

#determinant
print(torch.det(h))

#inverse
print(torch.inverse(h))


tensor([[3., 8., 5.],
        [6., 2., 9.],
        [5., 0., 4.]])
tensor(142.)
tensor([[ 0.0563, -0.2254,  0.4366],
        [ 0.1479, -0.0915,  0.0211],
        [-0.0704,  0.2817, -0.2958]])


###Special fxns

In [ ]:
k = torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
k

tensor([[4., 1., 1.],
        [2., 4., 7.]])

In [ ]:
#log
print(torch.log(k))

#exponents
print(torch.exp(k))

#sqrt
print(torch.sqrt(k))

#sigmoid
print(torch.sigmoid(k))

#softmax
print(torch.softmax(k,dim=0))

#relu
print(torch.relu(k))

tensor([[1.3863, 0.0000, 0.0000],
        [0.6931, 1.3863, 1.9459]])
tensor([[  54.5981,    2.7183,    2.7183],
        [   7.3891,   54.5981, 1096.6332]])
tensor([[2.0000, 1.0000, 1.0000],
        [1.4142, 2.0000, 2.6458]])
tensor([[0.9820, 0.7311, 0.7311],
        [0.8808, 0.9820, 0.9991]])
tensor([[0.8808, 0.0474, 0.0025],
        [0.1192, 0.9526, 0.9975]])
tensor([[4., 1., 1.],
        [2., 4., 7.]])


###Inplace Opertaions

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)
#print(m+n) #here it is creating new tensor , which is not optimal for space
#so we write
m.add_(n)
print(m)

tensor([[0.4890, 0.5887, 0.7340],
        [0.8497, 0.9112, 0.4847]])
tensor([[0.9436, 0.3904, 0.2499],
        [0.3206, 0.9753, 0.7582]])
tensor([[1.4325, 0.9792, 0.9839],
        [1.1703, 1.8865, 1.2429]])


###Copying a tensor

In [ ]:
p = torch.rand(2,3)
p

tensor([[0.6688, 0.2651, 0.2336],
        [0.5057, 0.5688, 0.0634]])

In [ ]:
#q = p #but in this method , here it refeerences a , not copy
q = p.clone() #here it makes copy
print(q)

tensor([[0.6688, 0.2651, 0.2336],
        [0.5057, 0.5688, 0.0634]])


###Tensor Operations on GPU

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = torch.device('cuda')

In [ ]:
#creating a new tensor on GPU
torch.rand((2,3),device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [ ]:
#move an existing tensor to GPU
z = torch.rand(2,3)
z

tensor([[0.8993, 0.2732, 0.3397],
        [0.1879, 0.5534, 0.2682]])

In [ ]:
b = z.to(device) #goes on GPU
b+5 # perform on GPU

tensor([[5.8993, 5.2732, 5.3397],
        [5.1879, 5.5534, 5.2682]], device='cuda:0')

###Reshaping Tensors

In [ ]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
#reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
#flatten - gives 1-d
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
b = torch.rand(2,3,4)
b

tensor([[[0.9556, 0.9761, 0.5934, 0.3124],
         [0.9431, 0.8519, 0.9815, 0.1132],
         [0.4783, 0.4436, 0.3847, 0.4521]],

        [[0.5569, 0.9952, 0.0015, 0.0813],
         [0.4907, 0.2130, 0.4603, 0.1386],
         [0.0277, 0.5662, 0.3503, 0.6555]]])

In [ ]:
#permute
b.permute(2,0,1).shape #interchange pos

torch.Size([4, 2, 3])

In [ ]:
#unsqueeze
#image size
c = torch.rand(226,226,3)
c.unsqueeze(0).shape #adds new dimension to a certain position

torch.Size([1, 226, 226, 3])

In [ ]:
#squeeze
c.squeeze(0).shape

torch.Size([226, 226, 3])

###Numpy and Pytorch

In [ ]:
import numpy as np

In [ ]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [ ]:
b = a.numpy()
b

array([1, 2, 3])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [ ]:
torch.from_numpy(c)

tensor([1, 2, 3])